### ISSUE TITLE
c_across() functions

### ISSUE THREAD

**Issue by monsadan** [STA518-Spring20/discussion#119]
I was trying to run the chunk where we complete the information and the `c_across( )`  function is not working, this is the error I'm getting: `Error in c_across(bty_f1lower:bty_m2upper) : could not find function "c_across"`.

I try to search the function using the console and used also the `dplyr::c_across()` but neither work.

Any idea what is happening?

**Comment by dykesb** [comment]
That's strange, because it's definitely a part of **dplyr**: https://dplyr.tidyverse.org/reference/across.html

Maybe see if there is an update for the **dplyr** package (Packages pane [lower right] >Update [along the top]). Otherwise, it might be the function that you're using it within.

Another thought, make sure you are working within the `Spring20_STA518_S01` Workspace of RStudio Cloud or you might need to install the **tidyverse**.

**Comment by monsadan** [comment]
Updating the package worked perfect! Thanks

**Comment by chycinsa** [comment]
Updating did not work for me

**Comment by fracassc** [comment]
I was getting the same issue after updating packages as well. Forcing a restart of the session in 'Session > Restart R' seems to have fixed it for me.

**Comment by monsadan** [comment]
I only updated the dplyr package. I don't know if this would help you.
