### ISSUE TITLE
Activity 4.6 trouble bootstrapping

### ISSUE THREAD

**Issue by jasonrsmith99** [STA518-Spring20/discussion#133]
I am having trouble figuring out how to bootstrap with the replicate, sample, and map functions. I would expect a correct output to have a length of 1000 and each element is the mean of each individual bootstrap. Here are the two functions I've tried.

```r
map_dbl(gss_educ, ~replicate(1000, sample(.x, replace = TRUE)) %>% 
                               mean())
```
This doesn't do what I expect since it's output is just one number (13.7) and not 1000 like I expect.

```r
replicate(1000, sample(gss_educ, replace = TRUE)) %>% 
  map_dbl(mean)
```
This function produces 1000 numbers like I expect but every number is 13.7 which means the function isn't bootstrapping.

I would appreciate any assistance with this.

**Comment by dykesb** [comment]
Use `gss_educ$educ` instead of `gss_educ` as `sample()` works on vectors (not a tibble/dataframe). Also, `replicate()` coerces the output to be an array/matrix and `map_dbl()` is looking for a list or atomic vector (an array/matrix is not an atomic vector). One way to avoid this is to include the `simplify = FALSE` argument in your `replicate()` call.

```
boots <- replicate(1000, 
                   sample(gss_educ$educ, 
                          size = nrow(gss_educ), # sample automatically samples the same size, so a bit redundant
                          replace = TRUE), 
                   simplify = FALSE)

mean_boot <- map_dbl(boots, mean)
```

**Comment by jasonrsmith99** [comment]
Thanks for the help! I got got by the simplify argument.
