### ISSUE TITLE
Team Activity Merge: Resolve Conflicts not available

### ISSUE THREAD

**Issue by KhileahWilliams** [STA518-Spring20/discussion#19]
When my team try'd to merge our project last night mine came up with a conflict and the resolve conflict button isn't available to click. How am I suppose to figure out where the conflict is??
![Screen Shot 2020-05-08 at 4 04 25 PM](https://user-images.githubusercontent.com/64782486/81444720-9cf08200-9145-11ea-80af-0b99a5ec09f9.png)

**Comment by dykesb** [comment]
Was this just an issue that you ran into or was it consistent with all of your Team Members?

**Comment by KhileahWilliams** [comment]
Just me.

**Comment by dykesb** [comment]
GitHub documentation is giving me this reasoning:

> Tip: If the Resolve conflicts button is deactivated, your pull request's merge conflict is too complex to resolve on GitHub.

It says to do some stuff in the Terminal that I might be able to help you with. Do you have time now? Otherwise, I have time Monday.

**Comment by KhileahWilliams** [comment]
I have time now

**Comment by dykesb** [comment]
I'm heading to the Bb Collaborate area - same place where our Tue/Thu sessions are.

**Comment by NickDuley** [comment]
Was there a solution found for this issue?

**Comment by dykesb** [comment]
We had to do a "pseudo hard reset":

We copied the current `master` branch `.Rmd` file and pasted it over @KhileahWilliams ' branch `.Rmd` file in RStudio. Then we Knitted and committed/pushed her new version to the repo. Once this happened, there are no merge conflicts since the two files are exactly the same.

I will explore a better solution for later activities in case this happens again, but for now this should work. Remember that you can always view previous versions of your documents (in this case, Khileah's actual work) by looking at the commit history on GitHub.

**Comment by jasonrsmith99** [comment]
if you have [GitHub desktop](https://desktop.github.com/) installed, you can resolve the conflicts there.

* At the bottom of the conflict error message, there is a link that reads 'Open in GitHub Desktop'. Clicking on that will open the program and walk you though cloning the repository on your local machine.
![Open in GH desktop](https://user-images.githubusercontent.com/64434718/81459209-beb12f80-916c-11ea-91bb-81f29dc747de.jpg)

* You'll have to take my word on this since I forgot to get a screenshot but a popup should appear near the top of the screen that tells you that there are conflicts with a link the view them. When you click on that, a window will pop up prompting you to open a specific file in a text editor (I use Notepad++).

![GitHubDesktop_PxDeYOJen5](https://user-images.githubusercontent.com/64434718/81459323-5282fb80-916d-11ea-98b7-edfe88b1a4cc.png)
_for the two manual conflicts, I chose to use the images from the master branch though it may not matter._

* Once you open the file in a text editor, you can resolve the conflicts like in the video (just remember to save the files when you're done editing).

* When all the conflicts have been resolved, press the blue 'commit' button at the bottom left, then the push button at the top (it would be where the 'fetch' button is in this picture)

![Push to github](https://user-images.githubusercontent.com/64434718/81459425-e0f77d00-916d-11ea-8216-880924a8008d.jpg)

* After that, you can return to the pull request page in your browser (you may need to refresh the page) and complete the merge.

![Yay](https://user-images.githubusercontent.com/64434718/81459453-071d1d00-916e-11ea-9b54-9a07c5f7c4e4.png)

**Comment by dykesb** [comment]
@jasonrsmith99 this is a great walkthrough! I would like to provide an alternative path to avoid installing software on computers. Since these conflict stem from the `.Rmd` file, I think I have an revised workflow that I will begin including in Activity instructions from here on out.

For those of you that are encountering this issue in Activity 1.2, you are welcome to use either of these solutions ([Jason's](https://github.com/STA518-Spring20/community/issues/19#issuecomment-626079198) or [mine](https://github.com/STA518-Spring20/community/issues/19#issuecomment-626048827)), which ever you feel most comfortable with.
