### ISSUE TITLE
Is a YAML different than a comment?

### ISSUE THREAD

**Issue by LauraRK** [STA518-Spring20/discussion#3]
I was just wondering where the term YAML comes from and if it means something different than the term "comment"?

**Comment by dykesb** [comment]
Others might be able to add more context, but it originally it was defined as "Yet Another Markup Language", then renamed to "YAML Ain't Markup Language" because it is has more of a data focus beyond markup languages.

See explanations from two of its creators on stackoverflow [Clark Evans](https://stackoverflow.com/a/6968501) and [Ingy döt Net](https://stackoverflow.com/a/18928199).

**Comment by LauraRK** [comment]
thank you for the context Professor.  That is helpful.
