### ISSUE TITLE
Application 7 part 6

### ISSUE THREAD

**Issue by dirksem** [STA518-Spring20/discussion#52]
For part 6 of Application 7, it seems like we are creating the same map we did for activity 0203 with the addition of "Also, color the states by division."  Do you mean we are supposed to overlay a map of the US and color the states on the overlay by division with the colored points for Denny's and La Quinta's also showing up?  I'm confused by what to produce.  Also, at the bottom of part 6 it says "delete this line once you verify the join worked and overwrite `dennys_laquinta`" but we didn't joint in that step. Is that a typo? Thanks!

**Comment by dykesb** [comment]
The map that you produce should be `fill`ed by `division` instead of being set as one solid color. Then, on top of this colored by division map, the colored points for Denny's and La Quinta's should be layered on top. It is ok if it doesn't look pretty, we will look into choosing specific colors next week.

That combo portion was a copy-paste issue - you can ignore that line. I will update my version.

**Comment by dykesb** [comment]
Notice that the `division` and the geometry shape information are in two different datafiles...
