### ISSUE TITLE
Application07 #4 Error: Result must have length 909, not 818301

### ISSUE THREAD

**Issue by bakjinn** [STA518-Spring20/discussion#54]
<img width="436" alt="Screen Shot 2020-05-27 at 10 36 12 AM" src="https://user-images.githubusercontent.com/23545297/83034774-9f3c5280-a006-11ea-8b97-bc0fd8d4f455.png">

I am not sure what this error means.

**Comment by dykesb** [comment]
Since Denny's and La Quinta have the same columns (in the same order), you want to "join" them by binding them *on top* of one another. The `full_join()` as you have it specified treating the `"states"` in each dataset as the same values, but all other columns differently. There are 909 obs in `laquinta`, but when you try to `full_join()` by state, there are multiple values in `dennys` (and even multiple entries of the same state in `laquinta`).

If you use `full_join()` you don't need a `by = ` argument when the columns are named exactly the same. For example, if datasets `a` and `b` have the exact same column names:

`bind_rows(a, b)` == `full_join(a, b)`

**Comment by bakjinn** [comment]
Thanks, I made the fix! The error is still pointing to the laquinta_us object with the same message and I still don't know what it means.

**Comment by dykesb** [comment]
You have two `laquinta_us` objects... which one is/was causing the issue? If you resolved this, what did you do?

**Comment by bakjinn** [comment]
I meant I changed the join statement. The error is flagging the first laquinta_us.

**Comment by dykesb** [comment]
You don't have a `country` column in your `laquinta` dataset.

**Comment by dykesb** [comment]
You should have been receiving a different error message as well.
