### ISSUE TITLE
Application05 #8

### ISSUE THREAD

**Issue by bakjinn** [STA518-Spring20/discussion#62]
<img width="388" alt="Screen Shot 2020-05-28 at 3 37 53 PM" src="https://user-images.githubusercontent.com/23545297/83185634-47324880-a0f9-11ea-8646-ab8ae6441728.png">
I am not sure where to begin calculating the average price for each great lakes region market and type combination. Do I take the AveragePrice for type and multiply that by region? If you could point me to the right resource, that would be helpful.

**Comment by dykesb** [comment]
You need to keep only the great lakes markets. You did something similarly up above when filtering using a vector for `major_regions`.

**Comment by bakjinn** [comment]
<img width="416" alt="Screen Shot 2020-05-28 at 8 54 13 PM" src="https://user-images.githubusercontent.com/23545297/83209095-6a72ed00-a125-11ea-8b64-6daa7c8f297d.png">
Once I've subset the data how to I combine the rows to get the average for the region and type?

**Comment by dykesb** [comment]
We haven't covered `subset()` you should be using `filter()` or `select()` to isolate information in a dataset.  For grouped summaries, go back to Activity 1.4.

**Comment by bakjinn** [comment]
<img width="327" alt="Screen Shot 2020-05-31 at 9 41 24 PM" src="https://user-images.githubusercontent.com/23545297/83368632-8d9cd700-a387-11ea-8e18-3ca9a7e734c4.png">

Is this the order of functions to use? I am not sure what this error means either.

**Comment by jasonrsmith99** [comment]
Maybe not relevant to the _group_by_ error but I think I see a few issues with your _select_ statement.

you can just list the columns you want to include in the function like
```r
select(var1, var2, var3)
``` 
as opposed of setting it equal to your variables.

I also see that one of the variables you're trying to select is "great_lakes_markets", which from what I can tell is a character vector instead of a variable in the _avocado_ dataset.
Try using _filter( )_ to pull out only the great lakes region.

**Comment by bakjinn** [comment]
<img width="275" alt="Screen Shot 2020-05-31 at 10 25 35 PM" src="https://user-images.githubusercontent.com/23545297/83370521-b0ca8500-a38d-11ea-965b-d784e21e8354.png">

I think I incorporated your feedback Jason! I am getting a new error though.

**Comment by jasonrsmith99** [comment]
I was able to get rid of the error message by removing the '=' in the select argument so it's just 'select(region, type, averageprice)'

I think that it's because you can define a new object with <- or = and R is thinking that you're trying to define a new object named select that contains region, type, and average price.

**Comment by bakjinn** [comment]
<img width="298" alt="Screen Shot 2020-06-01 at 7 30 08 PM" src="https://user-images.githubusercontent.com/23545297/83464267-56d5c800-a43e-11ea-9d66-76bf3b62175d.png">

I am getting an error that tells me that it can't subset columns that don't exist. x The column 'type' doesn't exist. I am not sure which line is causing the issue.

**Comment by jasonrsmith99** [comment]
You can run specific parts of code by highlighting it and pressing 
ctr + enter. You can go line by line by highlighting a line and all the lines before it. Just make sure you don't highlight the pipe in the last line.
something like this

![image](https://user-images.githubusercontent.com/64434718/83465234-ceb5e980-a462-11ea-90d5-639dbc4825fa.png)
