### ISSUE TITLE
Activity 3.1 Graph Issue

### ISSUE THREAD

**Issue by KhileahWilliams** [STA518-Spring20/discussion#89]
Hey so I'm not sure why my graph is empty and why it doesn't actually show the days of the week. Could someone steer me in the right direction?

![Screen Shot 2020-06-05 at 2 13 37 PM](https://user-images.githubusercontent.com/64782486/83909526-f6dd6b00-a736-11ea-86b0-3062abbe3a02.png)

![Screen Shot 2020-06-05 at 2 15 27 PM](https://user-images.githubusercontent.com/64782486/83909559-052b8700-a737-11ea-8739-a5d03f99f15e.png)

**Comment by dykesb** [comment]
It looks like you're using the wrong symbols in your `select()` line for specifying column names. They should be back-ticks (above Tab) not quotes. Otherwise, I would encourage you to go through this line by line to see if each additional pipe does what you expected it to.  For example make sure that `Rat_Sightings %>% select(...)` is actually selecting the columns that you hoped.  This can help you see where it breaks.
